# Generated by Django 3.0.8 on 2021-04-08 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='bank_id',
        ),
    ]
